name: gringo-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.26.4
  - scipy=1.11.4
  - scikit-learn=1.3.2
  - matplotlib
  - pillow=11.2.1
  - sympy=1.14.0
  - tqdm=4.66.1
  - fpdf=1.7.2
  - typing_extensions=4.13.2
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - certifi==2025.4.26
      - exceptiongroup==1.3.0
      - fastapi==0.115.2
      - filelock==3.18.0
      - fsspec==2025.5.1
      - h11==0.16.0
      - hf-xet==1.1.2
      - huggingface-hub==0.32.0
      - idna==3.10
      - Jinja2==3.1.3
      - joblib==1.3.2
      - MarkupSafe==3.0.2
      - networkx==3.2.1
      - packaging==25.0
      - pydantic==2.11.5
      - pydantic_core==2.33.2
      - python-dotenv==1.1.0
      - python-multipart==0.0.9
      - PyYAML==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.3
      - sentence-transformers==2.2.2
      - sniffio==1.3.1
      - starlette==0.40.0
      - threadpoolctl==3.6.0
      - torch==2.2.0
      - transformers==4.33.1
      - urllib3==2.4.0
      - uvicorn==0.34.2
      - zipp==3.21.0
