@echo off
echo Creating virtual environment...
python -m venv env
call env\Scripts\activate
echo Installing dependencies...
pip install -r requirements.txt
echo Launching AI agent dashboard...
python web\main.py
